language:
  scala
jdk:
  - openjdk11
scala:
  - 2.13.4
branches:
  only:
  - main
before_install:
  - nvm install 10
  - node --version
  - npm --version
install:
  - npm install -g serverless
script:
  - sbt assembly
after_script:
  - serverless deploy -v
