service: my-scala-lambda

provider:
  name: aws
  runtime: java8

package:
  artifact: target/scala-2.13/hello.jar

functions:
  hello:
    handler: hello.Handler
    events:
      - eventBridge:
          schedule: rate(10 minutes)